[package]
name = "couchbase-sys"
version = "0.1.0"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
build = "build.rs"
links = "libcouchbase"

[build-dependencies]
bindgen = "0.20"
pkg-config = "0.3"
cmake = "0.1"

[lib]
doctest = false
