[package]
name = "couchbase"
version = "1.0.0-alpha.1"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
keywords = ["couchbase", "database", "libcouchbase"]
categories = ["database", "asynchronous"]
description = "The official Couchbase Rust SDK."
repository = "https://github.com/couchbaselabs/couchbase-rs"
homepage = "https://github.com/couchbaselabs/couchbase-rs"
documentation = "https://docs.rs/couchbase"

[dependencies]
couchbase-sys = { path = "../couchbase-sys", version = "=1.0.0-alpha.1" }
futures = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
reqwest = "0.9"
env_logger = "0.6"