[package]
name = "couchbase"
version = "0.1.0"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
edition = "2018"

[dependencies]
futures = "0.1"
couchbase-sys = { path = "../couchbase-sys" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"