[package]
name = "couchbase"
version = "0.1.0"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
license = "Apache-2.0"
keywords = ["couchbase", "database", "futures", "libcouchbase", "async"]
description = "The Couchbase Rust SDK"
repository = "https://github.com/couchbaselabs/couchbase-rs"
homepage = "https://github.com/couchbaselabs/couchbase-rs"

[dependencies]
futures = "0.1"
parking_lot = "0.3"
couchbase-sys = { version = "0.1.0", path = "../couchbase-sys" }

[dev-dependencies]
# serde for the json examples
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
