[package]
name = "couchbase"
version = "0.2.0"
authors = ["Michael Nitschinger <michael.nitschinger@couchbase.com>"]
license = "Apache-2.0"
keywords = ["couchbase", "database", "futures", "libcouchbase", "async"]
categories = ["database", "asynchronous", "caching"]
description = "The Couchbase Rust SDK"
repository = "https://github.com/couchbaselabs/couchbase-rs"
homepage = "https://github.com/couchbaselabs/couchbase-rs"
documentation = "https://docs.rs/crate/couchbase"

[dependencies]
couchbase-sys = { version = "0.2.0", path = "../couchbase-sys" }

url = "1.4"
futures = "0.1"
parking_lot = "0.4"
log = "0.3"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dev-dependencies]
